### ISSUE TITLE
Difficulty training model with adversarial regularization

### ISSUE THREAD

**Issue by ckap100** [inspire-group/membership-inference-evaluation#2]
Hi,

I really enjoyed your paper. In particular, I think that your method of quantifying the membership inference vulnerability per data point is an excellent step towards understanding practical privacy guarantees. 

I am trying to replicate your results using tensorflow, but am unable to train a model using adversarial regularization. During training, my inference model quickly converges to predicting 0.5 for both train and reference data points, and does not learn any more in later epochs. I have tried a setup where I train the classifier for a few epochs in the beginning, before training the inference model once the classifier is more stable, but it still does not work.

After experiencing these issues, I wanted to train a model using the released code to make sure that I can replicate the results of the original paper. I tried to use the following repository (https://github.com/SPIN-UMass/ML-Privacy-Regulization), but the code doesn’t run off-the-shelf and I’m not sure of the correct modifications to make.

Could you please advise me on how you were able to train the models for your paper with adversarial regularization? Did you use the released code or did you re-implement the procedure yourself? 

Thank you for your time!

**Comment by lwsong** [comment]
Hi @ckap100 , thanks for your interest in our work.

For training with adversarial regularization, I mainly followed the released code by Nasr et al.
For your experiments, my suggestions are that you can try different hyperparameters, especially the weight of the adversarial regularization term; you can also check whether the inference model architecture follows the original paper or not: they use target model predictions plus one-hot encoded labels as training features for the inference model; also, the original code by Nasr et al. uses the logits (before softmax) to train the inference model, you can replace logits with probabilities (after softmax) to train the inference model, which should make inference model training easier.

Finally, because the target model is trained with the adversarial regularization term, it is normal that the inference predictions are close to 0.5 especially in later epochs.
